name: CI to Docker Hub

on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/n8n:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: Invoke webhoook
        run: | 
            CODE=`curl --write-out '%{http_code}' \
            --request POST \
            --header 'api-token: ${{ secrets.WEBHOOK_SECRET }}' \
            --header 'content-type: application/json' \
            --url '${{ secrets.WEBHOOK_URL }}' \
            --data '{ \
            "dockerImage": "${{ secrets.DOCKER_HUB_USERNAME }}/n8n:latest }'`
